- match: "jobs.utah.gov"
  name: "Department of Workforce Services"
  url: "http://jobs.utah.gov"
- match: "governor.utah.gov/dea"
  name: "Governor's Office of Planning and Budget"
  url: "http://governor.utah.gov/gopb"
- match: "geology.utah.gov"
  name: "Utah Geological Survey"
  url: "http://geology.utah.gov"
- match: "health.utah.gov"
  name: "Utah Department of Health"
  url: "http://health.utah.gov"
- match: "e911.utah.gov"
  name: "Utah 911 Committee"
  url: "http://e911.utah.gov"
- match: "mesowest"
  name: "MesoWest"
  url: "http://mesowest.utah.edu"
- match: "weber.ut.us"
  name: "Weber County, Utah"
  url: "http://weber.ut.us"
